---
title: Promise问题一   #文章标题
cover: 
type: 
tags: promise          #标签
categories:
- [JavaScript]
---

## 1.如何改变当前promise状态？
## 2.一个promise指定多个成功/失败回调函数，都会调用吗？

```javascript
    /*
        1.如何改变当前promise状态
        （1 resolve(value):如果当前是pending就会编程resolved
        （2 reject(reason): 如果当前pending就会变成rejected
        （3 抛出异常：如果当前是pending就会变成为rejected

        2.一个promise指定多个成功/失败回调函数，都会调用吗？
            对应状态都会调用
    */
    
    const p = new Promise((resolve, reject)=>{
        //resolve(1)  promise变为resolved成功状态
        //reject(2)   promise变为rejected失败状态
        //throw new Error('出错了') //抛出异常，promise变为rejected失败状态，reason为抛出的异常
        throw 3
    })
    p.then(
        value =>{},
        reason =>{console.log('reason', reason)} // 'reason'  3
    )
    p.then(
        value =>{},
        reason2 =>{console.log('reason2', reason2)} // 'reason2'  3
    )
```

<hr>

## 3.改变promise状态和指定回调函数谁先谁后？

```javascript
/*
        3.改变promise状态和指定回调函数谁先谁后？
            （1 都有可能，正常情况下先指定回调再改变状态，但也可以先改变状态再指定回调
            （2  如何先改变状态再指定回调？
                执行器中直接调用resolve() / reject()
                延迟更长时间再去调用then()
            （3 什么时候才能得到数据
                如果先指定的回调，当状态发生改变时，就会调用回调函数，得到数据
                如果先改变状态，当指定回调时，回调函数就会调用，得到数据
    */

    //常规：先指定回调函数，后改变的状态
    new Promise((resolve, reject)=>{
        setTimeout(() => {
            resolve(1)  //后改变的状态（同时指定数据），异步执行回调函数

        }, 1000);
    }).then(//先指定回调函数，保存当前指定的回调函数
        value =>{console.log('value', value)},
        reason =>{console.log('reason',reason)}

    )


    //先改变状态，后指定回调函数
    new Promise((resolve, reject)=>{
        resolve(2) //先改变的状态（同时指定数据）

    }).then(//后指定回调函数，异步执行回调函数
        value =>{console.log('value2', value)},
        reason =>{cosnole.log('reason', reason)}
    )

    const p3 = new Promise((resolve, reject)=>{
        setTimeout(() => {
            resolve(1)  //后改变的状态（同时指定数据），异步执行回调函数

        }, 1000);
    })
    setTimeout(() => {
        p3.then(//先指定回调函数，保存当前指定的回调函数
        value =>{console.log('value3', value)},
        reason =>{console.log('reason3',reason)}

    )
    }, 1100);
```
<hr>

## 4.promise.then()返回的新promise的 结果状态 由什么决定？

```javascript
/*  //then方法中的回调如果不指定返回值，下一个then默认调用的是成功的回调，值是undefined
        4.promise.then()返回的新promise的 结果状态 由什么决定？
            （1 简单表达：由then()指定的回调函数的执行结果决定
            （2 详细表达：
                如果抛出异常，新promise变为rejected，reason为抛出的异常
                如果返回的是非promise的任意值，新promise便为resolved，value为新返回的值
                如果返回的是另一个新的promise，此promise的结果就会成为新promise的结果
    */
    new Promise((resolve, reject)=>{
        resolve(1)
        // reject('w s shibai jieguo')
    }).then(
        value => {
            console.log('onResolved', value)
            // return 1
            // throw '出错了！'
            // throw '555！'
            // return Promise.reject('haha,you chenggong l !')  //注意，此处是构造函数Promise,不是实例
        },
        reason => {
            console.log('onRejected', reason)
            // throw '出错了！'
        }
    ).then(
        value => {
            console.log('onResolved2', value)
        },
        reason =>{
            console.log('onRejected2', reason)
        }
    )
```
<hr>


## 5.promise如何串连多个操作任务？

```javascript
/*
        5.promise如何串连多个操作任务？
            （1 promise的then()返回一个新的promise，可以开成then()的链式调用
            （2 通过then的链式调用串联的多个同步/异步任务
    */

    new Promise((resolve, reject) => {
        setTimeout(() => {
            console.log('执行任务1（异步）')
            resolve(1)
        }, 1000);
    }).then(
        value => {
            console.log('任务1结果：', value)
            console.log('执行任务2（同步）')
            return Promise.resolve(3)
        }
    ).then(
        value => { //如果要再then里的回调函数中继续执行异步操作，那就要用promise封装异步操作
            return new Promise((resolve, reject)=>{
                setTimeout(() => {
                console.log('我是异步任务3',value)
                resolve(4)
            }, 1000);
            })
        }
    ).then(
        value => {
            console.log('我是同步任务4', value)
        }
    )
```
<hr>

## 6.promise异常传/穿透（如果再then中没有指定失败的回调，系统会默认指定 reason => {throw reason}
## 7.中断promise链（ 当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数）

```javascript
    /*
        6.promise异常传/穿透（如果再then中没有指定失败的回调，系统会默认指定 reason => {throw reason}
            （1 当使用promise的hten链式调用时，可以再最后指定失败的问题
            （2 前面任何操作出了异常，都会传到最后失败的回调中处理

        7.中断promise链（ 当使用promise的then链式调用时，在中间中断，不再调用后面的回调函数）
            办法：在回调函数中返回一个pending状态的promise对象
    */
    new Promise((resolve, reject) => {
        reject(1)
    }).then(
        value => {
            console.log('成功回调', value)
            return 2
        }//默认：，reason => {throw reason}
    ).then(
    value => {
            console.log('成功回调', value)
            return 3
        }//默认：，reason => {throw reason}
    ).then(
    value => {
            console.log('成功回调', value)
            return 4
        }//默认：，reason => {throw reason}
    ).catch(
        reason => {
            console.log('最后指定的失败回调', reason)
            return 5
        }
    ).then(
    value => {
            console.log('成功回调', value)
            return new Promise(() => {})    //返回一个未指定状态的promise对象来中断后面的回调
        }
    ).then(
    value => {
            console.log('被中断的回调', value)
            
        }
    )
```